"use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContentWrapper } from "./utils/providers/ContentProvider";
import { ApolloClient, HttpLink, InMemoryCache } from "@apollo/client";
import { ApolloProvider } from "@apollo/client/react/index.js";
// import { ApolloProvider } from "@apollo/client/react";

const GQL_URL: string = process.env.NEXT_PUBLIC_GQL_API_URL || 'http://localhost:7100/';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// GraphQl client init 

const link = new HttpLink({
  uri: GQL_URL
});

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ApolloProvider client={client}>
          <ContentWrapper>
            {children}
          </ContentWrapper>
        </ApolloProvider>
      </body>
    </html>
  );
}
